plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    // Add the Google services Gradle plugin

    id("com.google.gms.google-services")

}

android {
    namespace 'com.gana.workspace'
    compileSdk 34

    defaultConfig {
        applicationId "com.gana.workspace"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    dataBinding{
        //noinspection DataBindingWithoutKapt
        enabled = true
    }
}
ext {

    retrofit_version = "2.11.0"
     lifecycle_version = "2.9.1"


}
dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.firebase.auth
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    // retrofit
    implementation libs.retrofit
    implementation libs.converter.scalars
    implementation libs.converter.gson

    // apache utills
    implementation libs.commons.lang3
    implementation libs.commons.collections4
    implementation libs.commons.text
    implementation libs.commons.math3

    // rx binding
    implementation libs.rxbinding
    implementation libs.rxbinding.material

    // Places and Maps SDKs
    implementation libs.places

    // rxjava
    implementation libs.rxjava
    implementation libs.rxandroid

    // room db
    runtimeOnly libs.androidx.room.runtime
    implementation libs.androidx.room.rxjava2
    annotationProcessor libs.androidx.room.compiler


    // glide
    implementation libs.glide

    // viewmodel
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"


    // Import the Firebase BoM

    implementation(platform(libs.firebase.bom))
    // TODO: Add the dependencies for Firebase products you want to use
    // When using the BoM, don't specify versions in Firebase dependencies
    // https://firebase.google.com/docs/android/setup#available-libraries

}